### ISSUE TITLE
Application is not authorized to perform this operation. Application must have one of the following scopes: DeviceManagementConfiguration.ReadWrite.All

### ISSUE THREAD

**Issue by longob** [ArunasFalcon/IntuneFirewallRulesMigration#1]
Hello,

Sorry for what may be a stupid question.  I am an Intune admin and have been assigned the Azure AD role "Intune Administrator".   I am not a global admin.  I'm not very familiar with Mg-Graph, but I installed PowerShell 7 and installed the Microsoft.Graph.Authentication and Az.Accounts modules, and then manually ran the Connect-MgGraph per the instructions.  The export went fine, but when I attempt to perform the input, no rules are imported.  The error message in the log file is shown below.  This is likely an error on my part, but I would greatly appreciate your help!  Is this possibly a role/permission error that my global admin can grant to me somehow?  Thank you.

"POST https://graph.microsoft.com/beta/deviceManagement/templates/4356d05c-a4ab-4a07-9ece-739f7c792910/createInstance
HTTP/1.1 403 Forbidden
Transfer-Encoding: chunked
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
client-request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
x-ms-ags-diagnostic: {""ServerInfo"":{""DataCenter"":""Central US"",""Slice"":""E"",""Ring"":""2"",""ScaleUnit"":""000"",""RoleInstance"":""DS1PEPF000051DF""}}
Date: Sun, 07 Aug 2022 15:38:00 GMT
Content-Type: application/json
Content-Encoding: gzip

{""error"":{""code"":""Forbidden"",""message"":""{\r\n  \""_version\"": 3,\r\n  \""Message\"": \""Application is not authorized to perform this operation. Application must have one of the following scopes: DeviceManagementConfiguration.ReadWrite.All - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx - Url: https://fef.msua04.manage.microsoft.com/DeviceManagementIntent/DeviceManagementIntentService/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/deviceManagement/templates%28%274356d05c-a4ab-4a07-9ece-739f7c792910%27%29/microsoft.management.services.api.createInstance?api-version=5020-08-21\"",\r\n  \""CustomApiErrorPhrase\"": \""\"",\r\n  \""RetryAfter\"": null,\r\n  \""ErrorSourceService\"": \""\"",\r\n  \""HttpHeaders\"": \""{}\""\r\n}"",""innerError"":{""date"":""2022-08-07T15:38:00"",""request-id"":""xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"",""client-request-id"":""xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx""}}}"

**Comment by ArunasFalcon** [comment]
Hi Iongob, first of all thanks for giving the modified script a shot and also thanks for your feedback. It's absolutely not a stupid question. I was connecting to Microsoft Graph API by using a service principal in the target tenant which does have that permission. I forgot to put that into the instructions. I haven't looked into how to do this without a service principal. I will look into it this week. In the mean time if you or someone else can create a service principal (= app registration in AAD), then these are the permissions I assigned (I did some other Intune and Sharepoint related stuff using Powershell so these are more permissions than necessary):
![powershell-intune-permissions](https://user-images.githubusercontent.com/69454581/183361854-4df198b7-c826-473f-8b2d-4371c9e6d2ae.png)
You need the app registration app id, secret, and the tenant id. Then sign on like this:

```
$tenant = '<tenant id here>'
$appid = '<app id here>'
$secret = '<secret value here>'
$sec = $secret | ConvertTo-SecureString -AsPlainText -Force
$credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $appid,$sec
Connect-AzAccount -Environment <sovereign cloud name or omit this parameter if you are connecting to global cloud> -ServicePrincipal -TenantId $tenant -Credential $credential
$token = (Get-AzAccessToken -ResourceTypeName MSGraph).Token
Connect-MgGraph -Environment <sovereign cloud name or omit this parameter if you are connecting to global cloud> -AccessToken $token
```

**Comment by ArunasFalcon** [comment]
Hi @longob, I checked the Azure role definitions and it seems there is no role with this permission attached. You could make a custom role, but I'd rather recommend you craete a service principal as described above and then do the import. I'll update the readme accordingly.

**Comment by ArunasFalcon** [comment]
I updated the readme with the permission info.
